### ISSUE TITLE
Super Resolution notebook not working locally 

### ISSUE THREAD

**Issue by SomeOrdinaryDude** [CompVis/latent-diffusion#101]
![image](https://user-images.githubusercontent.com/79510944/177502244-b10cfca3-adc6-4f3f-8966-b63269ac48e4.png)

First I must say that SR using this method is unreal, and beats anything else out there. I can get the colab working, but I am restrained by speed and memory. Using this with my RTX 3090 would be much better. However, trying to run the notebook locally works until this step. I don't know enough to really understand anything the error message provides. That's weird, since notebooks made for colab tends to just work when running locally in my experience.

**Comment by taoisu** [comment]
Seems to be a simple python error, change `print self.face_rec_model_path` to `print(self.face_rec_model_path)`

**Comment by SomeOrdinaryDude** [comment]
> 

Wow, there was an awful amount of that exact error in the python file. Though now I get another error, we will see if I open a issue or not. Might be able to fix it.

**Comment by lucellent** [comment]
Hey, were you able to run this locally?
