### ISSUE TITLE
All checkpoints and links on ommer-lab 404 not found

### ISSUE THREAD

**Issue by kjerk** [CompVis/latent-diffusion#14]
Hey thanks for all your work and the excellent readme!

There seems to be an issue with all files having moved or disappeared from https://ommer-lab.com/files/latent-diffusion/* , all the links are 404-ing now. The heibox links still work fine.

If the hosting is going to be an issue, it would be nice if the checkpoints were all uploaded as a Github release on this repo https://github.com/CompVis/latent-diffusion/releases , this way Github will cover the hosting indefinitely and it doesn't have to be a worry anymore for any future maintenence. See SwinIR's release as an example: https://github.com/JingyunLiang/SwinIR/releases

I'm super interested in text2img so hopefully these can be restored 😃 .
Thanks again!

**Comment by ablattmann** [comment]
Thx for informing and sorry for the inconvenience! Links should now be working again. Thx also for your recommendation regarding hosting, but this shouldn't be in issue anymore in the future :)
Text2img models will be released in the near future :)
Closing this right now,
cheers
