### ISSUE TITLE
Why not pass conditioning directly to the model instead of compare conditional one and unconditional one to "guide" model?

### ISSUE THREAD

**Issue by 522485449** [CompVis/latent-diffusion#146]
Hi, a question about conditioning. In this project, the key part about conditioning is:
`e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)`
`e_t = e_t_uncond + unconditional_guidance_scale * (e_t - e_t_uncond)`
Apparently, it passes the conditioning info ( when using text2img.py it's prompt encoded by BERT) right into the unet model. And it uses eps(unconditioned)  and eps(conditioned) with a "scale" factor to control how much the result is close to the prompt.

My question is, since the conditioning info is passed right into the unet model, why not use its result directly as the final output? Instead of compare conditional one and unconditional one to "guide" model?
` e_t = self.model.apply_model(x_in, t_in, c_in) #where c_in is conditioning only`

Another question is that, in disco diffusion, the conditioning way is using gradient to guide image generation.
`        new_mean = (
            p_mean_var["mean"].float() + p_mean_var["variance"] * gradient.float()
        )` 
Seems like in LDM, it use prompt+image to train the unet model, but in disco diffusion, it use clip to guide the inference process, not including the prompt info in its training process. Am I correct? If so, is there any logic why LDM choose to include prompt to train the model? Can it improve the model performance?

**Comment by 522485449** [comment]
figured it out

**Comment by pcicales** [comment]
Could you please explain @522485449
