### ISSUE TITLE
config file for conditional LDM

### ISSUE THREAD

**Issue by kaihe** [CompVis/latent-diffusion#15]
thank you for sharing this great work.

where can I find config files for these unconditional tasks, such as Text-conditional Image Synthesis, Super-resolution, Layout-to-Image Synthesis and Semantic Image Synthesis? 

the download links are merely ckpt files, and config files at configs/latent-diffusion are all unconditional tasks.

**Comment by kaihe** [comment]
found extra config files here: models\ldm

**Comment by karbalan** [comment]
did the txt2img256 config file work for you? if you tried it for the smaller conceptual captions pretrained model

**Comment by kaihe** [comment]
never tried that, the quality doesn't look good, maybe you want to try stable diffusion for txt2img
