### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by makisu0001** [CompVis/latent-diffusion#165]
this is output in terminal. is it due to hardware support?

Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 194366
LatentDiffusion: Running in eps-prediction mode
[1]    19548 segmentation fault (core dumped)  python scripts/txt2img.py --prompt  --plms --outdir ./output

**Comment by markgao-916** [comment]
maybe input "--prompt" error
