### ISSUE TITLE
question about disc_start

### ISSUE THREAD

**Issue by kaihe** [CompVis/latent-diffusion#18]
Thanks for this great work.

I am trying to train vq models with custom data, only realized that disc_start in vq configs are very different, 
for example,
[vq-f8-n256](https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/vq-f8-n256/config.yaml#L29) disc_start: 250001
[vq-f8](https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/vq-f8/config.yaml#L30) disc_start: 1

Any particular reasons that discrimator could start from 1?

**Comment by thunanguyen** [comment]
This is a number based on experiments, you can set any number if you see fit. But normally, you can try to set disc start after the reconstruction loss stops decreasing

**Comment by kaihe** [comment]
thanks

**Comment by pseudo-usama** [comment]
Can I know what this **disc_start** parameter is?
Is this related to some discriminator model in the process?
If so what is the need of a discriminator in a diffusion based model?
