### ISSUE TITLE
can not find ldm.data.openimages.FullOpenImagesTrain

### ISSUE THREAD

**Issue by hjq133** [CompVis/latent-diffusion#201]
I can't find the implementation  ldm.data.openimages.FullOpenImagesTrain

**Comment by hjq133** [comment]
it seems not relase

**Comment by ray-lee-94** [comment]
FullOpenImage without Open? @hjq133

**Comment by CreamyLong** [comment]
https://github.com/CreamyLong/stable-diffusion/blob/2c087336141cb7c7dea9beb5879d9e57e1197f6c/ldm/data/openimages.py#L473

**Comment by fengyang0317** [comment]
> https://github.com/CreamyLong/stable-diffusion/blob/2c087336141cb7c7dea9beb5879d9e57e1197f6c/ldm/data/openimages.py#L473

Hi @CreamyLong, thank for sharing. To use FullOpenImagesBase, unidentifiable_openimage_files.txt is needed. Do you have this file?
