### ISSUE TITLE
Question about FID calculation on ImageNet

### ISSUE THREAD

**Issue by GiannisPikoulis** [CompVis/latent-diffusion#206]
Hello.

I have a question about FID calculation on ImageNet. Is FID calculated per class and then the average FID across all classes is mentioned? Or do you just sample a random number of samples per class and compare it to the full dataset?

Thanks in advance.

**Comment by escorciav** [comment]
did you figure it out? I believe there is another issue claiming that they did replicate it the results using oai eval toolkit.

Do you know if this repo provides their own evaluation toolkit?
afaiu it's kinda similar, but different. Thus, unclear to me if they did

**Comment by escorciav** [comment]
#262
