### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by traveling121** [CompVis/latent-diffusion#210]
When I run "main.py", it shows as follows:

/data/latent-diffusion-main/venv/bin/python /data/latent-diffusion-main/main.py
Traceback (most recent call last):
File "/data/latent-diffusion-main/main.py", line 535, in
model = instantiate_from_config(config.model)
File "/data/latent-diffusion-main/ldm/util.py", line 79, in instantiate_from_config
if not "target" in config:
TypeError: argument of type 'NoneType' is not iterable

Process finished with exit code 1

Why and how to solve it?

**Comment by lx709** [comment]
you need to put a correct class name for the ‘target’ key in your config file.

**Comment by Yolanda2020** [comment]
Thanks

**Comment by traveling121** [comment]
> 

Thank you very much!
