### ISSUE TITLE
AttributeError: 'functools.partial' object has no attribute '__code__'

### ISSUE THREAD

**Issue by traveling121** [CompVis/latent-diffusion#223]
When I train the ldm model on ImageNet, it shows as follows:

Traceback (most recent call last):
  File "/data/latent-diffusion-main/main.py", line 726, in <module>
    trainer.fit(model, data)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 416, in fit
    self.train_loop.setup_fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 109, in setup_fit
    self.trainer.data_connector.attach_data(model, train_dataloader, val_dataloaders, datamodule)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 83, in attach_data
    self.attach_datamodule(model, datamodule, 'fit')
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 115, in attach_datamodule
    if is_overridden('val_dataloader', datamodule):
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/model_utils.py", line 42, in is_overridden
    is_overridden = instance_attr.__code__ is not super_attr.__code__
AttributeError: 'functools.partial' object has no attribute '__code__'

Please tell me how to solve the problem?

**Comment by thesisfinitobitte** [comment]
hey, i also have the same problem. Did you fix it?

**Comment by yudongjian** [comment]
> When I train the ldm model on ImageNet, it shows as follows:
> 
> Traceback (most recent call last): File "/data/latent-diffusion-main/main.py", line 726, in trainer.fit(model, data) File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 416, in fit self.train_loop.setup_fit(model, train_dataloader, val_dataloaders, datamodule) File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 109, in setup_fit self.trainer.data_connector.attach_data(model, train_dataloader, val_dataloaders, datamodule) File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 83, in attach_data self.attach_datamodule(model, datamodule, 'fit') File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 115, in attach_datamodule if is_overridden('val_dataloader', datamodule): File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/model_utils.py", line 42, in is_overridden is_overridden = instance_attr.**code** is not super_attr.**code** AttributeError: 'functools.partial' object has no attribute '**code**'
> 
> Please tell me how to solve the problem?

hello, i also have the same problem. Can you help me? thanks!

**Comment by yudongjian** [comment]
@Yolanda2020 @thesisfinitobitte  i also have the same problem. Can you help me? thanks!

**Comment by DavidKong96** [comment]
> @Yolanda2020 @thesisfinitobitte i also have the same problem. Can you help me? thanks!

hey,have you solved this problem? i met the same question.  thanks

**Comment by humanely** [comment]
How did you solve this?

**Comment by humanely** [comment]
@DavidKong96 @yudongjian @thesisfinitobitte ??

**Comment by humanely** [comment]
I found that there are shuffle flags but the method is not defined anywhere. That is why the missing code error shows as above. For anyone looking to solve this, just comment those 2 lines
```

#self.val_dataloader = partial(self._val_dataloader, shuffle=shuffle_val_dataloader)
.
.
#self.test_dataloader = partial(self._test_dataloader, shuffle=shuffle_test_loader)
```
