### ISSUE TITLE
Question about autoencoder

### ISSUE THREAD

**Issue by Yoonho-Na** [CompVis/latent-diffusion#227]
Hi

I'm currently training AutoencoderKL with my custom dataset.
I can see that reconstruction works well through tensorboard.
But the sampled image shows only noise like this.

<img width="261" alt="스크린샷 2023-01-30 오전 11 32 54" src="https://user-images.githubusercontent.com/53941554/215375356-9643167a-6980-474d-9a8b-e41bd496d5fa.png">

I think the sample images are obtained by this line of code below which is in the log_images function in autoencoder.py.
`self.decode(torch.randn_like(posterior.sample()))`

Is it normal just getting noise-like samples while reconstructing images so well? 
It feels really strange to me.

**Comment by IceClear** [comment]
The same with mine.

**Comment by GuHuangAI** [comment]
#187

**Comment by Yoonho-Na** [comment]
I'm still curious about this question.

What happens if we just map the latents to standard normal distribution by applying high KL-reg weight?

I'm assuming the reason why the author set low KL-reg is that if the KL-reg weight is high the latent is already gaussian even before diffusion process so the model can't learn diffusion process and denoising process.
Is my intuition correct?

**Comment by GuHuangAI** [comment]
@Yoonho-Na Yeah. It is the same thinking with me.
Besides,  I find the distribution mapped by auto-encoder (i call it dist-ae) is very different from the standard normal gaussian, and if I diffuse a white noise to the dist-ae, it's unsuccessful that the decoded image is still meaningless (200k steps). That's why there were a `scale_factor` in the diffusion process.

**Comment by Yoonho-Na** [comment]
@GuHuangAI Now I understand clearly. Thank you!

**Comment by theohsiung** [comment]
I'm facing a problem when i try to train my autoencoder:
Traceback (most recent call last):
  File "main.py", line 740, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

did this problem occured when you trained, please help me

**Comment by tomguluson92** [comment]
> I'm facing a problem when i try to train my autoencoder: Traceback (most recent call last): File "main.py", line 740, in if trainer.global_rank == 0: NameError: name 'trainer' is not defined
> 
> did this problem occured when you trained, please help me

Hi, have you ever solved this problem?
