### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by SaiyueLyu** [CompVis/latent-diffusion#245]
What is the correct data format for celebahq and LSUN?

I have celebahq in jpg format, how do I obtain the required .npy format as shown ```FileNotFoundError: [Errno 2] No such file or directory: 'data/celebahq/imgHQ05953.npy'```

And is there any other method to prepare LSUN, the original LSUN repo takes too long to run and stopped in the middle sometimes. 

And also the downloaded data is in lmdb format, how can I obtain the webp format as shown ```FileNotFoundError: [Errno 2] No such file or directory: 'data/lsun/churches/c11ef56b368fec4c3e35532a7c750a0a1941f912.webp'```

Any help would be appreciate!

**Comment by dydxdt** [comment]
I also have this problem. Can you share how to prepare the .npy and LSUN data? Thank you very much!

**Comment by zwxu064** [comment]
> What is the correct data format for celebahq and LSUN?
> 
> I have celebahq in jpg format, how do I obtain the required .npy format as shown `FileNotFoundError: [Errno 2] No such file or directory: 'data/celebahq/imgHQ05953.npy'`
> 
> And is there any other method to prepare LSUN, the original LSUN repo takes too long to run and stopped in the middle sometimes.
> 
> And also the downloaded data is in lmdb format, how can I obtain the webp format as shown `FileNotFoundError: [Errno 2] No such file or directory: 'data/lsun/churches/c11ef56b368fec4c3e35532a7c750a0a1941f912.webp'`
> 
> Any help would be appreciate!

How did you get these .npy files? I cannot see that from this repo's instruction. Thanks.

**Comment by zwxu064** [comment]
> I also have this problem. Can you share how to prepare the .npy and LSUN data? Thank you very much!

Did you get it for CelebA HQ?
