### ISSUE TITLE
CUDA out of memory with unconditional sampling

### ISSUE THREAD

**Issue by saswat0** [CompVis/latent-diffusion#286]
I'm facing GPU out of memory while trying unconditional sampling on the fairface dataset. Below is the script to trigger the job
```
python scripts/sample_diffusion.py -r models/ldm/ffhq256/model.ckpt -l ./logs_new/ -n 300 --batch_size 1 -c 1 -e 0
```
I've used a batch size of 1, and I'm using an A5000 GPU (24G), but the memory still overflows. Is the code buggy or are there any workarounds for sampling?

**Comment by RabJon** [comment]
I have a similar problem. I tried to set the batch size to 1 too, but as soon as the first attention layer is called, the OOM Error comes. Pytorch tries to allocate way to much memory as you can see in the error message below:

_torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 GiB (GPU 0; 31.75 GiB total capacity; 5.17 GiB already allocated; 20.61 GiB free; 10.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF_

I am not sure, if this problem can even be solved. I got this exception when I tried to increase the sampling size from 256 to 512. This leads me to the question if it is even possible to use images with a size bigger than 256 ?

**Comment by saswat0** [comment]
@RabJon For me, using the same config present inside `models/ldm/ffhq256` helped

**Comment by RabJon** [comment]
Thanks for your fast reply. I tried the config you mentioned, but it didn't work for my use case. Anyway I will open a proper issue, because I think the problem in my case is really the size of the images.
