### ISSUE TITLE
How to Implement Multiple Condition Inputs: Semantic Image + Text

### ISSUE THREAD

**Issue by jijunhao** [CompVis/latent-diffusion#293]
I have constructed a dataset that includes images along with two additional conditions(semantic image and text). What should I modify the code?  I noticed that in ddpm.py, a condition content is passed to the U-Net. Is this content a single condition? 

Do I need to re-written the get_input()？

**Comment by SahadevPoudel** [comment]
Hi, did you get any idea?

**Comment by zy-charon** [comment]
Hello, I would like to ask which file should be modified if only images are used as conditional input?
