### ISSUE TITLE
my   latent diffusion.  txt2img.yaml   run is error

### ISSUE THREAD

**Issue by yudongjian** [CompVis/latent-diffusion#318]
Hello, my yaml config, run CUDA_VISIBLE_DEVICES=1 python3 main.py --base configs/autoencoder/<config_spec>.yaml -t --gpus 0,   
is err, err eg:  hope get your help, Thanks!!! 

`Traceback (most recent call last):
  File "main.py", line 729, in <module>
    trainer.fit(model, data)
  File "/home/image1325_user/anaconda3/envs/yudongjian_23_ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 416, in fit
    self.train_loop.setup_fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/image1325_user/anaconda3/envs/yudongjian_23_ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 109, in setup_fit
    self.trainer.data_connector.attach_data(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/image1325_user/anaconda3/envs/yudongjian_23_ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 83, in attach_data
    self.attach_datamodule(model, datamodule, 'fit')
  File "/home/image1325_user/anaconda3/envs/yudongjian_23_ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 115, in attach_datamodule
    if is_overridden('val_dataloader', datamodule):
  File "/home/image1325_user/anaconda3/envs/yudongjian_23_ldm/lib/python3.8/site-packages/pytorch_lightning/utilities/model_utils.py", line 42, in is_overridden
    is_overridden = instance_attr.__code__ is not super_attr.__code__
AttributeError: 'functools.partial' object has no attribute '__code__'`

yaml eg:

`model:
  base_learning_rate: 2.0e-07
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 32
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler2
      params:
        warm_up_steps: [ 100 ]
        cycle_lengths: [ 200000 ]
        f_start: [ 1.e-8 ]
        f_max: [ 1. ]
        f_min: [ 1.e-8 ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 1280
        n_layer: 32

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.food.FoodTrain
      params:
        size: 256
        degradation: pil_nearest
    validation:
      target: ldm.data.food.FoodVal
      params:
        size: 256
        degradation: pil_nearest

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False
        log_images_kwargs:
          quantize_denoised: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False

  trainer:
    benchmark: True`

**Comment by humanely** [comment]
how did you solve this?
