### ISSUE TITLE
最后采样出现问题

### ISSUE THREAD

**Issue by xiaoxiaodadada** [CompVis/latent-diffusion#326]
我用了已经训练的AE和LDM已经生成好checkpoints，最后用CUDA_VISIBLE_DEVICES=3,6 python sample_diffusion.py -r logs/2023-11-16T08-53-37_custom-ldm-kl-8/checkpoints -l logs  -n 50 --batch_size 5  -c 50 -e 0来采样的时候，出现了问题Traceback (most recent call last):
 in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key model
    full_key: model
    object_type=dict
   我是哪里出现了问题，训练时候的权重文件，不是最后的model吗，救救我

**Comment by xin-xin-zy** [comment]
你已经解决这个问题了吗?如何解决的呢？

**Comment by xiaoxiaodadada** [comment]
解决啦，你要么把yaml文件和生成的权重文件放同级，要么改一下sample_diffusion.py的代码，变成这样读取，大约266行那里
`    else:
        assert os.path.isdir(opt.resume), f"{opt.resume} is not a directory"
        logdir = opt.resume.rstrip("/")
        ckpt = os.path.join(logdir, "checkpoints", "last.ckpt")

    base_configs = sorted(glob.glob(os.path.join(logdir, "configs/*-project.yaml")))`

**Comment by xin-xin-zy** [comment]
好的，我也解决了，谢谢

**Comment by xin-xin-zy** [comment]
已经解决了，非常感谢。可以问下利用LDM实现img2img，有什么参考和建议吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CompVis/latent-diffusion" ***@***.***&gt;;
发送时间:&nbsp;2023年11月28日(星期二) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CompVis/latent-diffusion] 最后采样出现问题 (Issue #326)






解决啦，你要么把yaml文件和生成的权重文件放同级，要么改一下sample_diffusion.py的代码，变成这样读取，大约266行那里
` else:
assert os.path.isdir(opt.resume), f"{opt.resume} is not a directory"
logdir = opt.resume.rstrip("/")
ckpt = os.path.join(logdir, "checkpoints", "last.ckpt")
base_configs = sorted(glob.glob(os.path.join(logdir, "configs/*-project.yaml")))`

**Comment by xiaoxiaodadada** [comment]
不好意思，我是做无条件图像生成的，对于img2img，也不是很了解(●'◡'●)

**Comment by bowen099** [comment]
> 解决啦，你要么把yaml文件和生成的权重文件放同级，要么改一下sample_diffusion.py的代码，变成这样读取，大约266行那里 ` else: assert os.path.isdir(opt.resume), f"{opt.resume} is not a directory" logdir = opt.resume.rstrip("/") ckpt = os.path.join(logdir, "checkpoints", "last.ckpt")
> 
> ```
> base_configs = sorted(glob.glob(os.path.join(logdir, "configs/*-project.yaml")))`
> ```

请问一下，前面的训练我知道要每一步都需要yaml配置文件，但是为什么最后推理测试也需要一个yaml文件啊，不是只需要最后训练的权重文件吗

**Comment by xiaoxiaodadada** [comment]
需要从配置文件里读编码器解码器和模型的路径

**Comment by bowen099** [comment]
> 需要从配置文件里读编码器解码器和模型的路径

谢谢大佬的解答！ 我还想请教一个问题！
比如我第一阶段的autoencoder使用的是KL f8的训练方式得到的权重，具体为：ldm.models.autoencoder.AutoencoderKL。然后我的第二阶段无论什么任务都必须要按照这个.AutoencoderKL来吗？
因为我注意到第二阶段的训练中有的提供的参考配置为：ldm.models.autoencoder.VQModelInterface
我需要这里改为保持第一阶段的类路径相同吗？
感谢

**Comment by xiaoxiaodadada** [comment]
是需要相同的，要不第二阶段的训练读第一阶段权重的时候也会报错

**Comment by bowen099** [comment]
多谢啦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月24日(周二) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CompVis/latent-diffusion] 最后采样出现问题 (Issue #326)


xiaoxiaodadada left a comment (CompVis/latent-diffusion#326)
 
是需要相同的，要不第二阶段的训练读第一阶段权重的时候也会报错
