### ISSUE TITLE
What information do autoencoders extract

### ISSUE THREAD

**Issue by Pang-0093** [CompVis/latent-diffusion#355]
Hi everyone, I have a question about autoencoders. I've noticed that a well-trained autoencoder can perform well on an unseen dataset. Does this mean autoencoders don't rely on the data distribution features? In other words, are the features extracted by autoencoders not the characteristics of the data distribution, but rather just some structural information used for compression-reconstruction? I am so curious about it. Can someone help me out?

**Comment by ALABAMABANANA** [comment]
> Hi everyone, I have a question about autoencoders. I've noticed that a well-trained autoencoder can perform well on an unseen dataset. Does this mean autoencoders don't rely on the data distribution features? In other words, are the features extracted by autoencoders not the characteristics of the data distribution, but rather just some structural information used for compression-reconstruction? I am so curious about it. Can someone help me out?

Hi Pang, have you figured out the reason? Now I am curious too lol, thanks and looking forward to your reply!
