### ISSUE TITLE
ModuleNotFoundError: No module named 'cutlit'

### ISSUE THREAD

**Issue by Polaris0421** [CompVis/latent-diffusion#366]
I try to run the code from latent diffusion model which clones taming-transformer, but I fail as" ModuleNotFoundError: No module named 'cutlit'". cutlit is not a python package, according to other issues I guess its a module in taming-transformer code, but I can't find anything related to cutlit in the project. Is this module deleted in newer version?

**Comment by humanely** [comment]
I think there is nobody to maintain this repo. It is abandoned for last 2 years.

**Comment by ader47** [comment]
Maybe in the yaml config file 
![image](https://github.com/CompVis/latent-diffusion/assets/46866849/8756bc6d-0397-43a2-8ad6-ae9d6311b407)
