### ISSUE TITLE
Vector quantization

### ISSUE THREAD

**Issue by hanchenwang** [CompVis/latent-diffusion#374]
I find the VQ layer is stacked to the end of the encoder of the first_stage AE. However, in your paper you said the VQ layer should be absorbed by the decoder instead. I am wondering if I missed anything. Otherwise, is it a conflict here or the VQ layer position is not important? Thank you!

**Comment by NITHISHM2410** [comment]
The latent diffusion models uses the VQModelInterface module. The method 'encode' from this class doesn't quantize, but the method 'decode' does the quantization, which is exactly what the paper described.

**Comment by hanchenwang** [comment]
Thank you for the clarification. I understand.
