### ISSUE TITLE
Alllow inference on CPU...

### ISSUE THREAD

**Issue by rlabs-oss** [CompVis/latent-diffusion#40]
Tried to allocate 128.00 MiB (GPU 0; 7.79 GiB total capacity; 6.19 GiB already allocated; 81.44 MiB free; 6.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

Setting CUDA_VISIBLE_DEVICES to -1 to force CPU results in no cuda devices found. 

Please allow CPU inference at the expense of time.

**Comment by illtellyoulater** [comment]
How much memory is needed for this to run?

**Comment by rlabs-oss** [comment]
384x320 is possible using GPU with 8GB VRAM - hacking at /ldm/models/diffusion/ddim.py and changing "cuda" to "cpu" where found worked. Its quite slow on Apple Silicon / M1 16GB, pytorch doesnt use the M1 GPU, inference is around 3 minutes for 256x256 image. The M1 CPU for 256x256 image is 6x slower than NVIDIA 2060S GPU.

**Comment by illtellyoulater** [comment]
Ok, I can confirm that with a 12GB VRAM GPU I could make it work up to 576 x 576, however I noticed that from an artistic point of view, the best results were generated at 256 x 256. If from there you increase resolution, the results will tend to be much more repetitive. Did anyone else notice that?
