### ISSUE TITLE
Training steps for autoencoder training

### ISSUE THREAD

**Issue by kosuke1701** [CompVis/latent-diffusion#5]
Thanks for sharing your great project.

How many steps did you train your autoencoders on ImageNet? It seems that there is no description of the number of training steps or epochs in the provided configuration files. Sorry if it's mentioned elsewhere.

**Comment by ablattmann** [comment]
Thx for your interest :) I've just updated the table containing pre-trained first stage models in the README.md. Train steps are now inlcuded

**Comment by CrossLee1** [comment]
@ablattmann 
for the training steps, what batch size and how many GPU cards do you use?

**Comment by forever208** [comment]
> [@ablattmann](https://github.com/ablattmann) for the training steps, what batch size and how many GPU cards do you use?

The config file says batch_size 12, but it is unclear how many GPUs were used
