### ISSUE TITLE
Training on LAION-400M 

### ISSUE THREAD

**Issue by srelbo** [CompVis/latent-diffusion#59]
Hi @rromb @ablattmann

Would you be able to add some documentation on how to generate/pre-process the dataset if we want to train on LAION-400M? 

Thanks! 🙏

**Comment by srelbo** [comment]
Hi  @rromb @ablattmann, would you be able to add the config files for `latent-diffusion` training on LAION-400M? Thanks!

**Comment by Weifeng-Chen** [comment]
+1
