### ISSUE TITLE
[Question] Is it possible to gradually diffuse/transform one given real image to another using diffusion model?

### ISSUE THREAD

**Issue by Karbo123** [CompVis/latent-diffusion#60]
Thanks for this great work. I'm quite interested in the possible applications of the (latent) diffusion model proposed in the impressive paper. Your works have shown many possible promising applications of this newly emerging generative modeling approach. However, I have another question that bothers me for several days. It would be great if you could give some advices or suggestions on this problem. The problem is actually a open one, and it's detailed below.

**Question**
Given an initial image (e.g. a 256x256 image with a red dog on it) as the starting image, can we use a diffusion model to diffuse/transform the initial image gradually, until it satisfies the expectation (e.g. conditioned on a text prompt of "a yellow cat"), the final image should be an image describing "a yellow cat".

**Difficulty**
As we know, the diffusion model assumes the initial image should be taken from the gaussian distribution. But in our situation, it is not the case. Our initial image is a real image, which I think it breaks the assumption.

I've directly tried to implement the thought in a most naive way, but it doesn't seem to work, because it generate some vague results.
It would be great if you could give some advices or suggestions on this problem. Thank you!!

**Comment by samedii** [comment]
You should be able to reverse sample to the noise that would have generated an image (with eta=0). See `reverse_sample` here https://github.com/crowsonkb/v-diffusion-pytorch/blob/master/diffusion/sampling.py for inspiration.

**Comment by Karbo123** [comment]
> You should be able to reverse sample to the noise that would have generated an image (with eta=0). See `reverse_sample` here https://github.com/crowsonkb/v-diffusion-pytorch/blob/master/diffusion/sampling.py for inspiration.

Thanks for the quick reply! This does help a lot! But I still wonder whether it is possible to find a way to **directly** convert an initial image to another, but not through an intermediate noise state? And if we do so anyway, is this process mathematically correct? Thanks a lot!!

**Comment by samedii** [comment]
What does **directly** mean?

**Comment by samedii** [comment]
I believe you've understood correctly. If you don't interpolate in some latent space (noise) then where would interpolate? You can just interpolate directly in image space but then the intermediate images will not be modified by the model at all and will look awful.

_Note that you maybe don't have to reverse sample all the way to full noise but you can probably interpolate in some intermediate noise level instead._

**Comment by ZhouCX117** [comment]
> For example, we may want to convert `imageA` to `imageB`. To my understanding, if I'm not wrong, by using reverse sampling, we are able to firstly convert the `imageA` to `noiseA`, and then use the `noiseA` as the initial noise and use guidance (e.g. text prompt) to convert `noiseA` to `imageB`. As we can see, this procedure requires an intermediate state `noiseA`, which is rather complicated and not straightforward. So my question is, is the intermediate state `noiseA` really necessary? Can we find another way to straightforward convert `imageA` to `imageB` without resorting to the intermediate noise `noiseA`?

Hi, @Karbo123. I just read your question, and I can't understand how to convert noiseA to imageB. In my understanding, noiseA should be converted to imageA. Could you please give me a favor?
