### ISSUE TITLE
At higher resolutions results looks much more repetitive than at lower ones

### ISSUE THREAD

**Issue by illtellyoulater** [CompVis/latent-diffusion#63]
Has anyone else notice this behavior?

**Comment by boopage** [comment]
I'm not sure how to solve it, but describe the problem here too: https://github.com/CompVis/latent-diffusion/issues/42#issuecomment-1100060049

**Comment by patniemeyer** [comment]
The networks were trained on images of a specific size and applying them to larger sizes I think they are going to tend to repeat structurally.  You see this happen in style transfer too to some extent.  There is probably a way around it by seeding with a low res image scaled at a certain point in the process.
