### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Limbicnation** [CompVis/latent-diffusion#79]
ImportError: /../../.local/lib/python3.8/site-packages/torchtext/_torchtext.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo

Please help.

**Comment by bartman081523** [comment]
do you had run with conda, as suggested
```
git clone https://github.com/CompVis/latent-diffusion
cd latent-diffusion
conda env create -f environment.yaml
conda activate ldm
```

**Comment by Limbicnation** [comment]
It worked, thanks!
