### ISSUE TITLE
what datasets are the 'Pretrained Autoencoding Models' trained on?

### ISSUE THREAD

**Issue by fido20160817** [CompVis/latent-diffusion#98]
Thanks for your work.

I am wondering what datasets are the 'Pretrained Autoencoding Models' trained on?

**Comment by rromb** [comment]
OpenImages: https://storage.googleapis.com/openimages/web/index.html

**Comment by tachikoma777** [comment]
@rromb   The "Pretrained Autoencoding Models" used for generate condition in the SR task, is it the same as the autoencoder in first phase? Thanks!
If so, is it appropriate to use encoder pretrained on high quality images to extract low quality condition?
